"""Step 2 (fullstack, provider=byos): collect the existing VPS to deploy onto.

Bring-your-own-server replaces the Hetzner step: instead of an API token used to
provision VMs, we just need the host Ansible should SSH into. The deploy SSH key
is generated in the ProjectStep; the user adds its public half to the VPS, and
points the domain's DNS A record at the host. No cloud account required.
"""

from __future__ import annotations

import socket
from pathlib import Path

import click
import yaml

from cli import wizard_output as ui

from ..base import WizardStep
from ..context import BootstrapContext

BYOS_INVENTORY_FILE = "inventory.byos.yml"


def write_byos_inventory(deployment_dir: Path, ctx: BootstrapContext) -> Path:
    """Write a static inventory for a single bring-your-own-server node.

    Reproduces the group names the Hetzner dynamic inventory plugin would create
    (``hcloud``, ``hcloud_type_master``) plus a ``production`` group, so the
    shared playbook targets the VPS without any provider-specific changes.
    """
    master_host = f"{ctx.project_name}-master-0"
    inventory = {
        "all": {
            "children": {
                # production is what `-l production` limits to; it contains the
                # whole hcloud subtree via group nesting.
                "production": {"children": {"hcloud": {}}},
                "hcloud": {
                    "children": {
                        "hcloud_type_master": {
                            "hosts": {
                                master_host: {
                                    "ansible_host": ctx.byos_host,
                                    "ansible_user": ctx.byos_ssh_user,
                                    # The playbook keys master-only tasks off this.
                                    "hcloud_labels": {"type": "master"},
                                }
                            }
                        }
                    }
                },
            }
        }
    }
    path = deployment_dir / BYOS_INVENTORY_FILE
    header = (
        "# Static inventory for bring-your-own-server (provider: byos).\n"
        "# Generated by `startup bootstrap`. The deploy SSH key is read from the\n"
        "# vault at deploy time, so no key material lives here.\n"
    )
    path.write_text(header + yaml.safe_dump(inventory, sort_keys=False))
    return path


def _looks_like_host(value: str) -> bool:
    """Accept an IPv4/IPv6 literal or a plausible hostname."""
    value = value.strip()
    if not value:
        return False
    for family in (socket.AF_INET, socket.AF_INET6):
        try:
            socket.inet_pton(family, value)
            return True
        except OSError:
            pass
    # Hostname: at least one dot, no spaces.
    return "." in value and " " not in value


class ByosStep(WizardStep):
    number = 2
    name = "Server (BYOS)"

    def check(self, ctx: BootstrapContext) -> bool:
        # Nothing persisted between runs — always collect the host.
        return False

    def run(self, ctx: BootstrapContext) -> None:
        ui.info(
            "Bring-your-own-server: kein Cloud-Account nötig. Du brauchst nur "
            "einen erreichbaren VPS (z.B. IONOS) mit frischem Ubuntu/Debian und "
            "root-SSH-Zugang."
        )

        # A host given on the command line is validated the same way, so a typo
        # surfaces here instead of as an SSH timeout minutes later.
        if ctx.byos_host and not _looks_like_host(ctx.byos_host):
            raise click.ClickException(
                f"'{ctx.byos_host}' is neither an IP address nor a hostname."
            )

        while not ctx.byos_host:
            host = ui.text_input("Server IP oder Hostname (z.B. 203.0.113.10)")
            if _looks_like_host(host):
                ctx.byos_host = host.strip()
                break
            ui.error("Bitte eine gültige IP-Adresse oder einen Hostnamen angeben.")

        if not ctx.non_interactive:
            ctx.byos_ssh_user = ui.text_input("SSH-User auf dem Server", default="root")

        ui.info(
            f"Stelle sicher, dass auf {ctx.byos_host} die Ports 22 (SSH), 80 und "
            "443 (HTTP/HTTPS für Let's Encrypt) offen sind und dass der DNS "
            f"A-Record von '{ctx.base_domain}' auf {ctx.byos_host} zeigt.\n"
            "Den Deploy-SSH-Key bekommst du im nächsten Schritt — den fügst du "
            f"einmalig in ~{'' if ctx.byos_ssh_user == 'root' else '/' + ctx.byos_ssh_user}"
            "/.ssh/authorized_keys auf dem Server ein."
        )
        ui.action_done(f"Server gesetzt: {ctx.byos_ssh_user}@{ctx.byos_host}")
