"""Step 3 (fullstack): clone template, generate keys, replace placeholders, vault."""

from __future__ import annotations

import contextlib
import shlex
import subprocess
import tempfile
from pathlib import Path

import click

from cli import wizard_output as ui
from cli.bootstrap import (
    TEMPLATE_VAULT_PASSWORD,
    _generate_docker_config_b64,
    _generate_ssh_keypair,
    template_replacements,
)
from cli.sync_commands import _run_command
from cli.template_commands import ANSWERS_FILE, render_project

from ..base import WizardStep, has_placeholders, prompt_user_public_key, repo_exists
from ..context import BootstrapContext
from ..vault_guard import (
    read_keychain_password,
    store_keychain_password,
    vault_is_decryptable,
    verify_rotation,
)

BYOS_DEPLOY_PUBLIC_KEY_FILE = "byos_deploy_key.pub"
BYOS_DEPLOY_PUBLIC_KEY_IGNORE = f"deployment/{BYOS_DEPLOY_PUBLIC_KEY_FILE}"


def kubernetes_namespace(ctx: BootstrapContext) -> str:
    """Return the namespace a bootstrapped project should deploy into.

    Existing projects predate namespaces and continue to use ``default``. New
    BYOS projects use their already validated kebab-case project name, so two
    projects pointed at one VPS are isolated without an extra mode switch.
    """
    return (
        ctx.project_name if ctx.provider == "byos" or ctx.shared_cluster else "default"
    )


def write_byos_deploy_public_key(deployment_dir: Path, public_key: str) -> Path:
    """Write the public deploy key users must add to their existing VPS."""
    key_path = deployment_dir / BYOS_DEPLOY_PUBLIC_KEY_FILE
    key_path.write_text(public_key.strip() + "\n")
    return key_path


def ensure_byos_deploy_public_key_ignored(project_dir: Path) -> None:
    """Keep the generated BYOS public key helper file out of git."""
    gitignore_path = project_dir / ".gitignore"
    existing = (
        gitignore_path.read_text().splitlines() if gitignore_path.exists() else []
    )
    if BYOS_DEPLOY_PUBLIC_KEY_IGNORE not in existing:
        with gitignore_path.open("a") as gitignore:
            if existing and existing[-1].strip():
                gitignore.write("\n")
            gitignore.write(BYOS_DEPLOY_PUBLIC_KEY_IGNORE + "\n")


# Appends only when the key is not already there, so a re-run of the wizard does
# not grow authorized_keys. The key travels on stdin: it never lands in the
# remote argv, and there is no quoting to get wrong.
_BYOS_INSTALL_DEPLOY_KEY = """
set -e
mkdir -p ~/.ssh
chmod 700 ~/.ssh
touch ~/.ssh/authorized_keys
chmod 600 ~/.ssh/authorized_keys
key=$(cat)
if ! grep -qxF "$key" ~/.ssh/authorized_keys; then
  printf '%s\\n' "$key" >> ~/.ssh/authorized_keys
fi
"""


def install_byos_deploy_key(ctx: BootstrapContext, public_key: str) -> bool:
    """Put the CI deploy key on the VPS using the operator's own SSH access.

    Whoever runs the wizard set that server up, so they can almost always reach
    it already. Returns False when they cannot - the caller then falls back to
    printing the command for them to run from wherever they do have access.
    """
    result = subprocess.run(
        [
            "ssh",
            "-o",
            "BatchMode=yes",
            "-o",
            "StrictHostKeyChecking=accept-new",
            "-o",
            "ConnectTimeout=10",
            f"{ctx.byos_ssh_user}@{ctx.byos_host}",
            _BYOS_INSTALL_DEPLOY_KEY,
        ],
        input=public_key.strip(),
        capture_output=True,
        text=True,
        check=False,
    )
    return result.returncode == 0


def byos_deploy_key_install_command(ctx: BootstrapContext, public_key: str) -> str:
    """Return the command that installs the deploy public key on the BYOS VPS."""
    user_host = f"{ctx.byos_ssh_user}@{ctx.byos_host}"
    remote = (
        "mkdir -p ~/.ssh && chmod 700 ~/.ssh && "
        "cat >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys"
    )
    return (
        f"printf '%s\\n' {shlex.quote(public_key.strip())} "
        f"| ssh {shlex.quote(user_host)} {shlex.quote(remote)}"
    )


class ProjectStep(WizardStep):
    number = 3
    name = "Create project"

    def check(self, ctx: BootstrapContext) -> bool:
        if ctx.mode != "github":
            return False

        if not ctx.project_dir.exists():
            if repo_exists(ctx.full_repo):
                ui.info(
                    f"Repository {ctx.full_repo} exists but has not been cloned locally."
                )
                return False
            return False

        if has_placeholders(ctx.project_dir):
            ui.info(
                "Repository exists with unresolved placeholders — applying settings..."
            )
            return False

        # "Configured" is not enough — the vault must actually be sealed with the
        # password we have in the Keychain. A previous run that rotated the vault
        # but died before persisting (or vice versa) leaves a healthy-looking dir
        # with an undecryptable vault; re-run the step instead of skipping it.
        keychain_password = read_keychain_password(ctx.project_name)
        if not vault_is_decryptable(ctx.deployment_dir, keychain_password):
            ui.info(
                "Cannot decrypt vault with the Keychain password "
                "— configuring secrets again..."
            )
            return False

        from cli.cluster_commands import configure_project_cluster

        if ctx.shared_cluster or ctx.cluster_config:
            configure_project_cluster(ctx)
        ctx.vault_password = keychain_password
        ui.skip_indicator(f"Project {ctx.project_name} already configured")
        return True

    def run(self, ctx: BootstrapContext) -> None:
        need_clone = not ctx.project_dir.exists()

        # 3a. Create a fresh application repository.
        if need_clone:
            ui.action_start("Creating project folder...")
            ctx.project_dir.mkdir(parents=True)
            _run_command(["git", "init", "-b", "main"], cwd=ctx.project_dir)
            ui.action_done("Project folder created")

        # 3b. SSH Keys
        user_public_key = prompt_user_public_key(non_interactive=ctx.non_interactive)
        ui.action_start("Generating CI SSH key...")
        with tempfile.TemporaryDirectory(prefix="bootstrap-ssh-") as ssh_tmp:
            ci_private_key, ci_public_key = _generate_ssh_keypair(
                ctx.project_name, Path(ssh_tmp)
            )
        ui.action_done("CI SSH key generated")

        # 3c. Placeholders
        ui.action_start("Configuring project...")
        replacements = template_replacements(
            project_name=ctx.project_name,
            base_domain=ctx.base_domain,
            additional_domains=ctx.additional_domains,
            github_username=ctx.github_username,
            docker_registry_host=ctx.docker_registry_host,
            postgres_version=ctx.postgres_version,
            k8s_namespace=kubernetes_namespace(ctx),
            ci_public_key=ci_public_key,
            user_public_key=user_public_key,
            deployment_ref=ctx.deployment_ref,
        )
        # Resuming a partly completed bootstrap must never overwrite application
        # edits or advance its recorded baseline. Updates have their own command.
        if not (ctx.project_dir / ANSWERS_FILE).exists():
            render_project(
                ctx.project_dir,
                replacements,
                source=ctx.template_source,
                version=ctx.template_version,
            )
        if ctx.deployment_ref != "main":
            workflow_text = "\n".join(
                path.read_text()
                for path in (ctx.project_dir / ".github/workflows").glob("*.yml")
            )
            if "@" + ctx.deployment_ref not in workflow_text:
                raise click.ClickException(
                    "This template does not support --deployment-ref; use a template with the deploy_ref Copier answer."
                )
        ui.action_done("Project configured")

        # 3d. Vault secrets
        ui.action_start("Encrypting secrets...")
        from cli.update_vault_secrets import update_secrets as update_vault_secrets
        from cli.vault.common import generate_random_secret

        ctx.vault_password = generate_random_secret(length=48)
        docker_config_b64 = _generate_docker_config_b64(ctx.github_username)

        field_random = ["k3s_token", "backend_db_password", "postgres_admin_password"]
        # Templates can opt into a stable Django signing key without putting
        # a secret into Copier answers or changing existing template schemas.
        if any(
            "backend_secret_key:" in path.read_text()
            for path in (ctx.deployment_dir / "group_vars").glob("*.yml")
        ):
            field_random.append("backend_secret_key")
        field_set = [
            ("postgres_admin_username", "admin"),
            ("docker_config_json_b64", docker_config_b64),
        ]
        if ctx.sentry_dsn:
            field_set.append(("backend_sentry_dsn", ctx.sentry_dsn))

        # ci_ssh_key doubles as the deploy key for byos (the local/CI deploy reads
        # it from the vault to SSH into the VPS). The hcloud token only exists for
        # the Hetzner provider.
        file_content = [("ci_ssh_key", ci_private_key)]
        if ctx.provider == "hetzner":
            file_content.append(("hcloud_token_production", ctx.hetzner_token))

        ok, _, pw_failed = update_vault_secrets(
            repo=str(ctx.deployment_dir),
            vault_password=TEMPLATE_VAULT_PASSWORD,
            vault_fields=field_random,
            set_field=field_set,
            set_file_content=file_content,
        )
        if not ok or pw_failed:
            raise click.ClickException("Could not encrypt secrets.")
        ui.action_done("Secrets encrypted")

        # 3e. Rotate vault password
        ui.action_start("Rotating vault password...")
        from cli.rotate_vault import rotate_vault_password as rotate_vault

        rotated = rotate_vault(
            repo=str(ctx.deployment_dir),
            old_password=TEMPLATE_VAULT_PASSWORD,
            new_password=ctx.vault_password,
            strict=True,
        )
        if not rotated:
            raise click.ClickException("Could not rotate vault password.")

        # Verify the end state before trusting it: the vault must decrypt with the
        # new password and must NOT decrypt with the public template constant.
        # Without this, a partial rotation silently leaves the vault sealed with
        # a well-known password while a different one lands in Keychain/CI.
        verify_rotation(ctx.deployment_dir, ctx.vault_password, TEMPLATE_VAULT_PASSWORD)
        ui.action_done("Vault password rotated")

        # 3f. Persist the vault password immediately — it only lived in memory so
        # far, and every later step (token cleanup, repo creation, push) can fail
        # and orphan the freshly rotated vault. Keychain first, fail loud.
        ui.action_start("Saving vault password in Keychain...")
        store_keychain_password(ctx.project_name, ctx.vault_password)
        ui.action_done("Vault password saved in Keychain")

        # 3g. Remove .bak files left behind by vault encryption
        for bak in ctx.project_dir.rglob("*.bak"):
            with contextlib.suppress(OSError):
                bak.unlink()

        # 3h. Provider-specific finishing touches
        if ctx.provider == "byos":
            # Write the static inventory and hand the user the deploy public key.
            from .byos import write_byos_inventory

            ui.action_start("Writing BYOS inventory...")
            inv_path = write_byos_inventory(ctx.deployment_dir, ctx)
            ui.action_done(f"Inventory written: {inv_path.name}")

            ui.action_start("Writing BYOS deploy key...")
            deploy_key_path = write_byos_deploy_public_key(
                ctx.deployment_dir, ci_public_key
            )
            ensure_byos_deploy_public_key_ignored(ctx.project_dir)
            ui.action_done(f"Deploy key written: {deploy_key_path.name}")

            # CI workflows are the same generic caller stubs the template ships
            # for every target: they call the reusable workflows in
            # deploy-your-startup and pass only VAULT_PASSWORD. BYOS vs. Hetzner
            # is decided in Ansible (inventory + vault), not in the workflow YAML.

            authorized_keys = (
                "/root/.ssh/authorized_keys"
                if ctx.byos_ssh_user == "root"
                else f"/home/{ctx.byos_ssh_user}/.ssh/authorized_keys"
            )
            ui.info(
                "Add this public deploy key to "
                f"{authorized_keys} on the server so Ansible can connect:\n\n"
                f"{ci_public_key}\n"
                "Schnellweg:\n"
                f"  {byos_deploy_key_install_command(ctx, ci_public_key)}\n"
                f"The local helper file {deploy_key_path} is in .gitignore "
                "and will not be committed."
            )
        from cli.cluster_commands import configure_project_cluster

        configure_project_cluster(ctx)
        if ctx.provider == "hetzner":
            # Token cleanup — immediately after vault encryption.
            ui.action_start("Cleaning up temporary Hetzner token...")
            from cli.hetzner.credentials import delete_token

            delete_token()
            ui.action_done("Temporary Hetzner token removed")
